### ISSUE TITLE
scroll down when loading more crashes

### ISSUE THREAD

**Issue by zuoshu** [cymcsg/UltimateRecyclerView#110]
Demo crashes when continue scrolling down if it's still loading.
log:
07-06 12:42:23.305  10840-10840/com.marshalchen.ultimaterecyclerview.demo E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.marshalchen.ultimaterecyclerview.demo, PID: 10840
    java.lang.NullPointerException
            at com.marshalchen.ultimaterecyclerview.UltimateRecyclerView.enableShoworHideToolbarAndFloatingButton(UltimateRecyclerView.java:367)
            at com.marshalchen.ultimaterecyclerview.UltimateRecyclerView$3.onScrolled(UltimateRecyclerView.java:337)
            at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:3634)
            at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1401)
            at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2209)

**Comment by cymcsg** [comment]
Thank you for reporting this.You can try the latest version of URV and help us to find out if the problem is existed.

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue.
