### ISSUE TITLE
UltimateDifferentViewTypeAdapter crashes with Invalid Data binder error

### ISSUE THREAD

**Issue by aprofromindia** [cymcsg/UltimateRecyclerView#126]
I would like to create a accordion style Recycler view with different types of view Items. I am using UltimateDifferentViewTypeAdapter and am trying to notify a binder that items in a certain range: -

-mAdapter).notifyBinderItemRangeInserted(mAdapter.getUpdateDataBinder(), position+ 1, --ordersSize);-

Have been inserted or deleted.... but upon doing that I get a crash with the following stack trace. I am using 0.3.10 of URV.

java.lang.IllegalArgumentException: Invalid Data Binder
            at com.marshalchen.ultimaterecyclerview.UltimateDifferentViewTypeAdapter.getEnumFromBinder(UltimateDifferentViewTypeAdapter.java:138)
            at com.marshalchen.ultimaterecyclerview.UltimateDifferentViewTypeAdapter.getPosition(UltimateDifferentViewTypeAdapter.java:64)
            at com.marshalchen.ultimaterecyclerview.UltimateDifferentViewTypeAdapter.notifyBinderItemRangeInserted(UltimateDifferentViewTypeAdapter.java:99)
            at com.intwash.android.ui.presenters.OrderHistoryPresenter.onSectionStateChanged(OrderHistoryPresenter.java:132)
            at com.intwash.android.ui.adapters.OrderHistoryAdapter$ActiveOrderBinder$1.onClick(OrderHistoryAdapter.java:214)
            at android.view.View.performClick(View.java:4084)
            at android.view.View$PerformClick.run(View.java:16966)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)

**Comment by cymcsg** [comment]
Could you show more code of your program which can help us find the bug?

**Comment by aprofromindia** [comment]
its pretty standard i setup the binders in a subclass of UltimateDifferentViewTypeAdapter. I have 4 different types of binders for 4 different types of view.

Later when I changed data by adding/removing items from a List inform the specific binder through : - 

notifyBinderItemRangeInserted(mAdapter.getUpdateDataBinder(), position+ 1, --ordersSize);

BTW - I have a question is there a better way to add/remove data in such situations please?
