### ISSUE TITLE
when i use in fragment,it seems report an error like this

### ISSUE THREAD

**Issue by hjw541988478** [cymcsg/UltimateRecyclerView#131]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView$ViewHolder.shouldIgnore()' on a null object reference
            at android.support.v7.widget.RecyclerView.findMinMaxChildLayoutPositions(RecyclerView.java:2799)
            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2586)
            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2971)
            at android.view.View.layout(View.java:16678)
            at android.view.ViewGroup.layout(ViewGroup.java:5328)
            at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:562)
            at android.view.View.layout(View.java:16678)
            at android.view.ViewGroup.layout(ViewGroup.java:5328)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
            at android.view.View.layout(View.java:16678)
            at android.view.ViewGroup.layout(ViewGroup.java:5328)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:16678)
            at android.view.ViewGroup.layout(ViewGroup.java:5328)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
            at android.view.View.layout(View.java:16678)
            at android.view.ViewGroup.layout(ViewGroup.java:5328)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:16678)
            at android.view.ViewGroup.layout(ViewGroup.java:5328)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
            at android.view.View.layout(View.java:16678)
            at android.view.ViewGroup.layout(ViewGroup.java:5328)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:16678)
            at android.view.ViewGroup.layout(ViewGroup.java:5328)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
            at android.view.View.layout(View.java:16678)
            at android.view.ViewGroup.layout(ViewGroup.java:5328)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:16678)
            at android.view.ViewGroup.layout(ViewGroup.java:5328)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
            at android.view.View.layout(View.java:16678)
            at android.view.ViewGroup.layout(ViewGroup.java:5328)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:16678)
            at android.view.ViewGroup.layout(ViewGroup.java:5328)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2319)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2032)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6643)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
            at android.view.Choreographer.doCallbacks(Choreographer.java:590)
            at android.view.Choreographer.doFrame(Choreographer.java:560)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at an

**Comment by hjw541988478** [comment]
I found that when I comment the method "setCustomLoadMoreView" , everything goes ok ,so may the matter comes from the method.

**Comment by hjw541988478** [comment]
adapter.setCustomLoadMoreView(getActivity().getLayoutInflater().inflate(R.layout.custom_bottom_progressbar, mRecyclerView.mRecyclerView,false));

I  just forgot to make the 3rd param'value be false.
