### ISSUE TITLE
IllegalStateException: ViewStub must have a non-null ViewGroup viewParent

### ISSUE THREAD

**Issue by alirezaaa** [cymcsg/UltimateRecyclerView#183]
Hi,

I think you're setting something null and because of that, Android throws an exception.

**The complete trace is:**
```
java.lang.IllegalStateException: ViewStub must have a non-null ViewGroup viewParent
            at android.view.ViewStub.inflate(ViewStub.java:292)
            at com.marshalchen.ultimaterecyclerview.UltimateRecyclerView.setEmptyView(UltimateRecyclerView.java:183)
            at com.collect_up.c_up.fragments.ShopPagerFragment$2.onFailure(ShopPagerFragment.java:145)
            at com.collect_up.c_up.helpers.Pagination$5.onFailure(Pagination.java:123)
            at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:379)
            at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:195)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

The error was thrown because of following line that I've set.
```
mRecyclerView.setEmptyView(R.layout.empty_list_view_cause_get_data_error);
```
**And the used layout content is:**
```
<TextView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center"
    android:text="@string/coudnt_load_data" />
```

**Comment by yudhir** [comment]
ViewStub is null.
I encountered the same when I tried setting a different Loading and LoadFailed Views.
Once you set the empty view , you cannot set another view  again because The stub is already inflated.

**Comment by alirezaaa** [comment]
So this is a bug and should be fixed! because I must be able to set the layout dynamically. Thanks.

**Comment by firasalkafri** [comment]
Any updates with this?

**Comment by alirezaaa** [comment]
@firasalkafri Not yet :(
@cymcsg Sir we're waiting for a big update. I'm using this library inside my very huge project and I really want to see regular updates. Thanks.

**Comment by cymcsg** [comment]
@alirezaaa  It's very kind of you. As I am really too busy these days I can hardly find enough time to improve the library regularly . I'll try to fix bugs and enhance the library.

**Comment by lulee007** [comment]
@alirezaaa   try use `UltimateRecyclerView.getEmptyView()` and  remove its children view, then  inflate and add your custom view   into its parent view
```
View view=ultimateRecyclerView.getEmptyView();
if(view!=null){
     ViewGroup viewGroup= ((ViewGroup) view.getParent());
     viewGroup.removeView(view);
viewGroup.addView(LayoutInflater.from(viewGroup.getContext()).inflate(errorViewRsid,null));
}else{
ultimateRecyclerView.setEmptyView();
}
```
