### ISSUE TITLE
java.lang.AbstractMethodError: abstract method not impleme

### ISSUE THREAD

**Issue by alirezaaa** [cymcsg/UltimateRecyclerView#234]
Hi,

I'm getting following exception after removing items with an animation.

```
11-12 12:31:39.406  26044-26044/xxx E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.AbstractMethodError: abstract method not implemented
            at android.support.v7.widget.RecyclerView$ItemAnimator.animateDisappearance(RecyclerView.java)
            at android.support.v7.widget.RecyclerView.animateDisappearance(RecyclerView.java:3046)
            at android.support.v7.widget.RecyclerView.access$700(RecyclerView.java:144)
            at android.support.v7.widget.RecyclerView$4.processDisappeared(RecyclerView.java:416)
            at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:201)
            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2931)
            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
            at android.view.View.layout(View.java:15204)
            at android.view.ViewGroup.layout(ViewGroup.java:4793)
            at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:581)
            at android.view.View.layout(View.java:15204)
            at android.view.ViewGroup.layout(ViewGroup.java:4793)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
            at android.view.View.layout(View.java:15204)
            at android.view.ViewGroup.layout(ViewGroup.java:4793)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:15204)
            at android.view.ViewGroup.layout(ViewGroup.java:4793)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
            at android.view.View.layout(View.java:15204)
            at android.view.ViewGroup.layout(ViewGroup.java:4793)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:15204)
            at android.view.ViewGroup.layout(ViewGroup.java:4793)
            at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
            at android.view.View.layout(View.java:15204)
            at android.view.ViewGroup.layout(ViewGroup.java:4793)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:15204)
            at android.view.ViewGroup.layout(ViewGroup.java:4793)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
            at android.view.View.layout(View.java:15204)
            at android.view.ViewGroup.layout(ViewGroup.java:4793)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:15204)
            at android.view.ViewGroup.layout(ViewGroup.java:4793)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
            at android.view.View.layout(View.java:15204)
            at android.view.ViewGroup.layout(ViewGroup.java:4793)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:15204)
            at android.view.ViewGroup.layout(ViewGroup.java:4793)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2257)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2004)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6350)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
            at android.view.Choreographer.doCallbacks(Choreographer.java:591)
            at android.view.Choreographer.doFrame(Choreographer.java:561)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
            at android.os.Handler.handleCallback(Handler.java:730)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5419)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
            at dalvik.system.NativeStart.main(Native Method)
```

I think if you upgrade your library to the newer build tools version and update your dependencies, this problem should be fixed. I'm using build tools v23 currently.

***Note:*** after disabling the animation, the problem has fixed but I want to use that animation!

**Comment by cymcsg** [comment]
I'll try to upgrade the Recyclerview  and find out if this can fix the problem.

**Comment by alirezaaa** [comment]
I hope to found new versions here soon ;) Thanks.

**Comment by liangjianqi** [comment]
I have the same problem

**Comment by mustafa-demir** [comment]
+1 I have the same problem.

**Comment by nienlm-hhtv** [comment]
+1 same problem :(
