### ISSUE TITLE
Report bug of StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by hzy87email** [cymcsg/UltimateRecyclerView#25]
<pre><code>
Process: com.marshalchen.ultimaterecyclerview.demo, PID: 19937
    java.lang.StringIndexOutOfBoundsException: length=0; index=0
            at com.marshalchen.ultimaterecyclerview.demo.SimpleAdapter.getHeaderId(SimpleAdapter.java:87)
            at com.timehop.stickyheadersrecyclerview.HeaderPositionCalculator.hasNewHeader(HeaderPositionCalculator.java:43)
            at com.timehop.stickyheadersrecyclerview.StickyRecyclerHeadersDecoration.getItemOffsets(StickyRecyclerHeadersDecoration.java:60)
            at android.support.v7.widget.RecyclerView.getItemDecorInsetsForChild(RecyclerView.java:2744)
            at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:5543)
            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1332)
            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1269)
            at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1097)
            at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:957)
            at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:2797)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
            at android.view.Choreographer.doCallbacks(Choreographer.java:574)
            at android.view.Choreographer.doFrame(Choreographer.java:543)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5050)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
            at dalvik.system.NativeStart.main(Native Method)

</code></pre>

**Comment by cymcsg** [comment]
Thank you. Could you show more of your code or the circumstance of how the bug appears.

**Comment by cymcsg** [comment]
You can try the latest version on dev branch.
I think the latest version fixed the bug.
