### ISSUE TITLE
I don't wanner ParallaxHeader ,but if i don't user setParallaxHeader it will throw java.lang.NullPointerException

### ISSUE THREAD

**Issue by harveyhaha** [cymcsg/UltimateRecyclerView#313]
`java.lang.NullPointerException
                                                                                               at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5117)
                                                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4416)
                                                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4326)
                                                                                               at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1955)
                                                                                               at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1364)
                                                                                               at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1327)
                                                                                               at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:556)
                                                                                               at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2713)
                                                                                               at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3011)
                                                                                               at android.view.View.layout(View.java:14849)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                               at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:562)
                                                                                               at android.view.View.layout(View.java:14849)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                               at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
                                                                                               at android.view.View.layout(View.java:14849)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                               at android.view.View.layout(View.java:14849)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                               at android.view.View.layout(View.java:14849)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                               at android.view.View.layout(View.java:14849)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                               at android.view.View.layout(View.java:14849)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                               at android.view.View.layout(View.java:14849)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                               at android.view.View.layout(View.java:14849)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                               at android.view.View.layout(View.java:14849)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                               at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2044)
                                                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1801)
                                                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1057)
                                                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5666)
                                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                                               at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                                               at android.os.Handler.handleCallback(Handler.java:733)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                               at android.os.Looper.loop(Looper.java:136)
                                                                                               at android.app.ActivityThread.main(ActivityThread.java:5072)
                                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                           	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java`

**Comment by jjhesk** [comment]
i cannot understand your question.

**Comment by harveyhaha** [comment]
I don't want to use ParallaxHeader ,so i comment the method setParallaxHeader() in DebugLoadMoreActivity.class and it throws NullPointerException

The following is the commented code
`        ultimateRecyclerView.setParallaxHeader(getLayoutInflater().inflate(R.layout.parallax_recyclerview_header, ultimateRecyclerView.mRecyclerView, false));
`

**Comment by jjhesk** [comment]
you also have to switch the adapter to non-header support adapter.

**Comment by jjhesk** [comment]
@harveyhaha  please refer to the latest update of the library. There were some bugs from the previous [issue](https://github.com/DMCApps/NavigationFragment/issues/12) and it is now fixed and patched.
