### ISSUE TITLE
java.lang.NullPointerException: Attempt to write to field 'int android.support.v7.widget.RecyclerView$ViewHolder.mItemViewType' on a null object

### ISSUE THREAD

**Issue by asdfcjf** [cymcsg/UltimateRecyclerView#372]
at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5465)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4689)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4599)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1988)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1384)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1347)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1174)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1031)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1504)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2461)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.View.dispatchTouchEvent(View.java:9295)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.app.Activity.dispatchTouchEvent(Activity.java:2799)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.View.dispatchPointerEvent(View.java:9515)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
05-05 15:13:41.388 20154-20154/com.softinfo.zdl.smartPhone E/AndroidRuntime: 	at android.view.ViewRootImpl$InputStage

**Comment by jjhesk** [comment]
what is ur setup

**Comment by skysmileereryday** [comment]
how to solve this problem?

**Comment by jjhesk** [comment]
@skysmileereryday maybe you can illustrate from your source code first.

**Comment by castrojr913** [comment]
The same error, in my scenario the message is read instead of write from field.... I'm using the easyRegularAdapter and meanwhile I'm scrolling down, the app crashes

**Comment by millytwm1228** [comment]
test

**Comment by juanagu** [comment]
Same error, any solution? I'm Using the EasyRegularadapter

**Comment by millytwm1228** [comment]
Hi
I use UltimateDifferentViewTypeAdapter
It can work perfectly.
you can change this adapter.

From Taiwan , Milly

2016-12-02 21:49 GMT+08:00 Juan Ignacio Agu <notifications@github.com>:

**Comment by MalderAndroid** [comment]
Check if onCreateViewHolder doesn't return null.

**Comment by guiltydarkness1313** [comment]
thanks for the answer

**Comment by edcastrohit** [comment]
public class WrapContentLinearLayoutManager extends LinearLayoutManager {
    //... constructor
    public WrapContentLinearLayoutManager(Context context, int orientation, boolean reverseLayout) {
        super(context, orientation, reverseLayout);
    }

    public WrapContentLinearLayoutManager(Context context) {
        this(context, VERTICAL, false);
    }

    @Override
    public void onLayoutChildren(RecyclerView.Recycler recycler, RecyclerView.State state) {
        try {
            super.onLayoutChildren(recycler, state);
        } catch (Exception e) {
            if (EdConstant.LOG_ENABLED) {
                Timber.e("Error, IndexOutOfBoundsException in RecyclerView happens" + e);
            }
        }
    }
}
