### ISSUE TITLE
Refreshing and scrolling will cause an exception.

### ISSUE THREAD

**Issue by Wolftein** [cymcsg/UltimateRecyclerView#44]
Pulling to refresh and immediatly scrolling will cause the given exception:

```   
 java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 6(offset:6).state:13
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4041)
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3999)
            at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1892)
            at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:419)
            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1301)
            at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1128)
            at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:985)
            at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1204)
            at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:1951)
            at android.view.View.dispatchTouchEvent(View.java:7713)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2210)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2329)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1568)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2458)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2277)
            at android.view.View.dispatchPointerEvent(View.java:7893)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3947)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3826)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
            at android.v
```

**Comment by cymcsg** [comment]
Thank you.Could you describe more details about the bug so I can try to locate it? I have tried to pull to refresh and immediatly scrolling,but nothing happens

**Comment by Wolftein** [comment]
I Currently using this code (Kotlin)
```
    override fun onActivityCreated(p0: Bundle?) {
        ..
        mRecycler.setDefaultOnRefreshListener({ doCollectionLoad(true) })
    }

    private fun doCollectionLoad(p0: Boolean) {
        val nAdapter = (mRecycler.getAdapter() as AbsViewHolderAdapter<*>)
        nAdapter.setNotifyOnChange(false)
        nAdapter.clear()

        if (!p0) {
            mContainer.setViewState(MultiStateView.ViewState.LOADING)
        }

        (getActivity() as MainActivity)
                .getServiceAttachedOf()
                .getModule()
                .getResolver()
                .getFeaturedPlaylists(mRecycler.getAdapter().getItemCount(), LIMIT_PER_ACTION)
                .subscribeOn(Schedulers.newThread())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(
                        { p2 -> doCollectionAdd(p2, p0) },
                        { p2 -> doCollectionAdd(null, p0) })
    }

    private fun doCollectionAdd(p0: UeCollection<UePlaylist>?, p1: Boolean) {
        val nAdapter = (mRecycler.getAdapter() as AbsViewHolderAdapter<*>)

        if (p0 != null) {
            mPageLimit = p0.mTotal
            nAdapter.addAll(p0.mArray)
            nAdapter.setNotifyOnChange(true)
            nAdapter.notifyDataSetChanged()
        } else {
            nAdapter.addAll(emptyList<UePlaylist>())
        }
        mContainer.setViewState(MultiStateView.ViewState.CONTENT)
    }
```

**Comment by cr3ativ3** [comment]
It sounds related - in example app if you scroll after refresh while Add animation is playing, new added view overlaps the header image.

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue.
