### ISSUE TITLE
OnLoadMoreListener

### ISSUE THREAD

**Issue by mohammadaminha** [cymcsg/UltimateRecyclerView#481]
Im getting 
UltimateRecyclerView$OnLoadMoreListener.loadMore(int, int)' on a null object reference 
after coming back to list !
Here's the full log:

java.lang.NullPointerException: Attempt to invoke interface method 'void com.marshalchen.ultimaterecyclerview.UltimateRecyclerView$OnLoadMoreListener.loadMore(int, int)' on a null object reference
                                                                         at com.marshalchen.ultimaterecyclerview.UltimateRecyclerView.scroll_load_more_detection(UltimateRecyclerView.java:476)
                                                                         at com.marshalchen.ultimaterecyclerview.UltimateRecyclerView.access$300(UltimateRecyclerView.java:61)
                                                                         at com.marshalchen.ultimaterecyclerview.UltimateRecyclerView$2.onScrolled(UltimateRecyclerView.java:498)
                                                                         at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4722)
                                                                         at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4891)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:616)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by jjhesk** [comment]
make sure the pointer is not removed.
