### ISSUE TITLE
Error in load more...

### ISSUE THREAD

**Issue by mori-honest** [cymcsg/UltimateRecyclerView#59]
My code just work fine before adding these lines but I get this error when adding load more:

    mRecyclerView.enableLoadmore();
        adapter.setCustomLoadMoreView(LayoutInflater.from(getActivity())
                .inflate(R.layout.progressbar_bottom_load_more_recycler_view, null));
        mRecyclerView.setOnLoadMoreListener(new UltimateRecyclerView.OnLoadMoreListener() {
            @Override
            public void loadMore(int itemsCount, final int maxLastVisiblePosition) {
                new Handler().postDelayed(new Runnable() {
                    public void run() {
                        // todo: insert new items at the end of list....
                        // adapter.insert("More " + moreNum++, simpleRecyclerViewAdapter.getAdapterItemCount());
                        CallLogAdapter.HistoryItem historyItem = new CallLogAdapter.HistoryItem();
                        adapter.insert(historyItem, adapter.getAdapterItemCount());
                        adapter.insert(historyItem, adapter.getAdapterItemCount());
                        adapter.insert(historyItem, adapter.getAdapterItemCount());
                    }
                }, 3000);
            }

The error:

    06-02 10:50:49.217    9898-9898/co.a.m E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: co.a.m , PID: 9898
    java.lang.IndexOutOfBoundsException: Invalid index 30, size is 30
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at co.a.m.view.adapter.CallLogAdapter.getItem(CallLogAdapter.java:105)
            at co.a.m.view.adapter.CallLogAdapter.onBindViewHolder(CallLogAdapter.java:90)
            at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:4805)
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4106)
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3999)
            at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1892)
            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1338)
            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1301)
            at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1128)
            at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:985)
            at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:3458)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:799)
            at android.view.Choreographer.doCallbacks(Choreographer.java:599)
            at android.view.Choreographer.doFrame(Choreographer.java:558)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:784)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5872)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
            at dalvik.system.NativeStart.main(Native Method)

Invalid index 30, size is 30??????!!!!!!!!

**Comment by cymcsg** [comment]
I do not know what your adapter is.Maybe you can read the code of SimpleAdapter. I think it caused by wrong getItemCount.

**Comment by mori-honest** [comment]
I'd used the sample code and found out that you pass an empty item in getItem() method to solve this. but why?

**Comment by cymcsg** [comment]
The last item of the basic adapter is ``loading more`` item.So if you want to use loadingmore and stickyheader at the same time, you should set a empty value to the last item.
It's really ugly,but I need some time to make it better.

**Comment by mori-honest** [comment]
:)
Thanks for your great work!
wish you luck!
