### ISSUE TITLE
insert exceptions

### ISSUE THREAD

**Issue by jjhesk** [cymcsg/UltimateRecyclerView#81]
there are still some exceptions from the outofbound. I had simply just doing insert data into the adapter

like so:
simpleRecyclerViewAdapter.insert("my formatted data", 0);
                        

  Process: com.hb.editoral, PID: 22072
    java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 4(offset:4).state:17
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4041)
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3999)
            at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1892)
            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1338)
            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1301)
            at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1128)
            at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:985)
            at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1204)
            at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:1951)
            at android.view.View.dispatchTouchEvent(View.java:8388)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2424)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2158)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2569)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1743)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2739)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2530)
            at android.view.View.dispatchPointerEvent(View.java:8578)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4028)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3894)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3456)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3509)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3475)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3585)

**Comment by cymcsg** [comment]
Could you show more details about the problem? I have try ``findViewById(R.id.add).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                simpleRecyclerViewAdapter.insert("newly added item", 0);
            }
        });`` which in demo,but it works fine.

**Comment by jjhesk** [comment]
I have done some childfragment test with the recycler thing. It happens on open and close the app. something from its lifecycles. I will keep tracing and give u a more detail occurrence.

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue.
