### ISSUE TITLE
NPE on touch loadMore layout...

### ISSUE THREAD

**Issue by mori-honest** [cymcsg/UltimateRecyclerView#87]
when LoadMore layout is shown if user touches it, app crashes.

    java.lang.NullPointerException
            at com.marshalchen.ultimaterecyclerview.swipelistview.SwipeListViewTouchListener.setFrontView(SwipeListViewTouchListener.java:151)
            at com.marshalchen.ultimaterecyclerview.swipelistview.SwipeListViewTouchListener.onTouch(SwipeListViewTouchListener.java:827)
            at com.marshalchen.ultimaterecyclerview.swipelistview.SwipeListView.onInterceptTouchEvent(SwipeListView.java:689)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1859)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2169)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1613)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2539)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2117)
            at android.view.View.dispatchPointerEvent(View.java:8005)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4274)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4153)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3688)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3738)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3707)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3818)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3715)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3875)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3688)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3738)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3707)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3715)
            at android.view.ViewRootImpl$In

**Comment by cymcsg** [comment]
Could you show more details of your code?

**Comment by mori-honest** [comment]
layout: 

     <com.marshalchen.ultimaterecyclerview.SwipeableUltimateRecyclerview
        android:id="@+id/ultimate_recycler_view"
        xmlns:swipe="http://schemas.android.com/apk/res-auto"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        swipe:onlyOneOpenedWhenSwipe="true"
        swipe:swipeBackView="@+id/back"
        swipe:swipeCloseAllItemsWhenMoveList="true"
        swipe:swipeFrontView="@+id/frontItemLayout"
        swipe:swipeMode="left"
        swipe:swipeOffsetLeft="180dp"/>

main:
    
       mRecords = new ArrayList<>();
        mLinearLayoutManager = new LinearLayoutManager(getActivity());
        mRecyclerView.setLayoutManager(mLinearLayoutManager);
        mRecyclerView.setHasFixedSize(true);
        mAdapter = new CallLogAdapter(getActivity(), mRecords);

        //Add sticky header
        StickyRecyclerHeadersDecoration headersDecor = new StickyRecyclerHeadersDecoration(mAdapter);
        mRecyclerView.addItemDecoration(headersDecor);
        mRecyclerView.addItemDecoration(new HorizontalDividerItemDecoration.Builder(getActivity()).build());
        mRecyclerView.setDefaultOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener() {
            @Override
            public void onRefresh() {
                refreshList();
            }
        });
        //mRecyclerView.addItemDividerDecoration(getActivity());

        mAdapter.setCustomLoadMoreView(LayoutInflater.from(getActivity())
                .inflate(R.layout.progressbar_bottom_load_more_recycler_view, null));
        mRecyclerView.setAdapter(mAdapter);

adapter:

    public class CallLogAdapter extends UltimateViewAdapter {
    private final LayoutInflater mInflater;
    private final Context mContext;
    HashMap<String, Contact> mContactHashMap = new HashMap<>();
    private String iso2Name;
    private List<HistoryRecord> mItems = new ArrayList<>();
    private Long[] mHeaderItems;


    public CallLogAdapter(Context context, List<HistoryRecord> items) {
        if (!EventBus.getDefault().isRegistered(this)) {
            EventBus.getDefault().register(this);
        }
        UserContactProvider.getInstance(context).startLoadContactsAsync();

        mInflater = LayoutInflater.from(context);
        mContext = context;
        setItems(items);

        iso2Name = PhoneNumberUtils.getInstance(mContext).getDefaultIso2Name();
    }

    @Override
    public UltimateRecyclerviewViewHolder onCreateViewHolder(ViewGroup viewGroup) {
        View v = mInflater.inflate(R.layout.row_history, viewGroup, false);
       /* v.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent motionEvent) {
                if (motionEvent.getAction() == MotionEvent.ACTION_DOWN && v instanceof ViewGroup) {
                    ((ViewGroup) v).requestDisallowInterceptTouchEvent(true);
                }
                return false;
            }
        });*/
        ItemViewHolder vh = new ItemViewHolder(v);
        return vh;
    }


    @Override
    public void toggleSelection(int pos) {
        super.toggleSelection(pos);
    }

    @Override
    public void setSelected(int pos) {
        super.setSelected(pos);
    }

    @Override
    public void clearSelection(int pos) {
        super.clearSelection(pos);
    }

    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder viewHolder, int position) {
        try {
            final HistoryRecord item = getItem(position);

            TextView txtContactName = (TextView) viewHolder.itemView.findViewById(R.id.txt_contact_name);
            ImageView img_contact = (CircularImageView) viewHolder.itemView.findViewById(R.id.img_contact);
            TextView txtAppType = (TextView) viewHolder.itemView.findViewById(R.id.txt_application_type);
            TextView txtAppInfo = (TextView) viewHolder.itemView.findViewById(R.id.txt_application_info);
            TextView txtAppTime = (TextView) viewHolder.itemView.findViewById(R.id.txt_application_time);
            Button swipeDetail = (Button) viewHolder.itemView.findViewById(R.id.swipeDetails);
            Button swipeDelete = (Button) viewHolder.itemView.findViewById(R.id.swipeDelete);

            if (txtAppInfo == null || txtAppTime == null || txtAppType == null || img_contact == null) {
                return;
            }
            try {
                item.from_formatted = PhoneNumberUtils.getE164PhoneNumber(item.from, iso2Name);
            } catch (NumberParseException e) {
                e.printStackTrace();
            }

            Contact contact = mContactHashMap.get(item.from_formatted);
            if (contact != null && contact.image != null && contact.image.size() > 0) {
                Bitmap bm = contact.image.get(0);
                if (bm != null) {
                    img_contact.setImageBitmap(bm);
                }
            } else {
                try {
                    img_contact.setImageDrawable(mContext.getResources().getDrawable(R.drawable.contact_default));
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

            //todo: set number from contacts.
            String formattedNumber;
            if (contact != null) {
                formattedNumber = contact.name;
            } else {
                formattedNumber = item.from_formatted;
            }
            txtContactName.setText(formattedNumber);

            //todo: Format date and time by value
            txtAppTime.setText(DateUtils.getFormattedTime(item.date));

            final String duration = DateUtils.getDurationBreakdown(TimeUnit.SECONDS.toMillis(item.duration));
            txtAppInfo.setText(duration);
            //todo:set app type
            Track lastTrack = item.tracks.get(item.tracks.size() - 1);
            if (lastTrack.type.equals(APP_TYPE_MENU)) {
                txtAppType.setText(APP_TYPE_CALL_ICON + " " + mContext.getString(R.string.call));
            } else if (lastTrack.type.equals(APP_TYPE_FORWARD)) {
                try {
                    lastTrack.data.forwardedTo_formatted = PhoneNumberUtils.getE164PhoneNumber(lastTrack.data.forwardedTo, iso2Name);
                } catch (NumberParseException e) {
                    e.printStackTrace();
                }

                Contact forwardedToContact = mContactHashMap.get(lastTrack.data.forwardedTo_formatted);
                String formattedForwardedTo;
                if (forwardedToContact != null) {
                    formattedForwardedTo = forwardedToContact.name;
                } else {
                    formattedForwardedTo = lastTrack.data.forwardedTo;
                }
                txtAppType.setText(APP_TYPE_FORWARD_ICON + " " + formattedForwardedTo);

            } else if (lastTrack.type.equals(APP_TYPE_VOICEMAIL)) {
                txtAppType.setText(APP_TYPE_VOICEMAIL_ICON);

            } else if (lastTrack.type.equals(APP_TYPE_RECEIVE_FAX)) {
                txtAppType.setText(APP_TYPE_FAX_ICON + " " + mContext.getString(R.string.fax));
                txtAppInfo.setText(lastTrack.data.pages > 1 ? lastTrack.data.pages + " Pages" : lastTrack.data.pages + " Page");

            } else if (lastTrack.type.equals(APP_TYPE_ANNOUNCEMENT)) {
                txtAppType.setText(APP_TYPE_ANNOUNCEMENT_ICON + " " + mContext.getString(R.string.announcement));

            } else if (lastTrack.type.equals(APP_TYPE_SMS)) {
                txtAppType.setText(APP_TYPE_SMS_ICON + " " + lastTrack.data.text);

            }
            swipeDetail.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    String message = mContext.getString(R.string.from) + ": " + item.from_formatted + "\n" +
                            mContext.getString(R.string.Duration) + ": " + duration + "\n" +
                            mContext.getString(R.string.date) + ": " + item.date + "\n";
                    MaterialDialog dialog = new MaterialDialog.Builder(mContext)
                            .title(mContext.getString(R.string.details))
                            .content(message)
                            .positiveText(mContext.getString(R.string.ok))
                            .show();
                }
            });


            swipeDelete.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {

                }
            });

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public RecyclerView.ViewHolder onCreateHeaderViewHolder(ViewGroup viewGroup) {
        View view = mInflater.inflate(R.layout.stick_header_item_date_call_log, viewGroup, false);
        return new RecyclerView.ViewHolder(view) {
        };
    }

    @Override
    public void onBindHeaderViewHolder(RecyclerView.ViewHolder viewHolder, int i) {
        TextView textView = (TextView) viewHolder.itemView.findViewById(R.id.stick_text);
        String date = getItem(i).date;
        if (date != null) {
            textView.setText(DateUtils.getInstance(mContext).getFormattedDate(date));
        }
    }

    @Override
    public int getAdapterItemCount() {
        return mItems.size();
    }

    @Override
    public long generateHeaderId(int i) {
        if (i < mHeaderItems.length && i >= 0) {

            return mHeaderItems[i];
        } else return i;
    }

    private void generateHeaderIdList() {
        int size = mItems.size();
        mHeaderItems = new Long[size];
        for (int i = 0; i < size; i++) {
            HistoryRecord item = getItem(i);
            if (item == null || item.date == null) {
                mHeaderItems[i] = (long) i;
            } else
                mHeaderItems[i] = DateUtils.getFormattedDateForHeaderId(item.date);
        }
        notifyDataSetChanged();
    }

    public List<HistoryRecord> getItems() {
        return mItems;
    }

    public void setItems(List<HistoryRecord> items) {

        clear();
        mItems.addAll(items);

        //sortList();
        generateHeaderIdList();
        notifyDataSetChanged();
    }


    public void insert(HistoryRecord item) {
        List<HistoryRecord> items = new ArrayList<>(mItems);
        items.add(item);

        mItems.add(item);

        //sortList();
        generateHeaderIdList();
        notifyDataSetChanged();
    }

    public void insert(List<HistoryRecord> items) {
        if (items != null) {
            List<HistoryRecord> currentItems = new ArrayList<>(mItems);

            currentItems.addAll(items);

            mItems.addAll(items);

            //sortList();
            generateHeaderIdList();
            notifyDataSetChanged();
        }
    }

    public void swapPositions(int from, int to) {
        swapPositions(mItems, from, to);
    }

    public void insert(HistoryRecord item, int position) {
        insert(mItems, item, position);
        generateHeaderIdList();
    }

    public void remove(int position) {
        remove(mItems, position);
    }

    public void clear() {
        clear(mItems);
    }

    public HistoryRecord getItem(int position) {
        if (position < mItems.size())
            return mItems.get(position);
        else return new HistoryRecord();
    }

    private void sortList() {
        Collections.sort(mItems, new Comparator<HistoryRecord>() {
            public int compare(HistoryRecord o1, HistoryRecord o2) {
                if (o1.date == null || o2.date == null)
                    return 0;
                return o2.date.compareTo(o1.date);
            }
        });
        notifyDataSetChanged();
    }

    // This method will be called when a MessageEvent is posted
    @Subscribe
    public void onEvent(UserContactsLoaded event) {
        mContactHashMap = event.getContacts();
        notifyDataSetChanged();
    }

**Comment by mori-honest** [comment]
This makes my app crash as soon as user touches the loading layout or some other places(I don't figured out where). so  please fix this as soon as possible. Thanks for your great work.

**Comment by cymcsg** [comment]
Do you think it will help you if you disable the swipe method on the last item(in fact it's the loading more view)?

**Comment by mori-honest** [comment]
Yes. I think the error will go away by 90% chance.
How can i do that? can you explain how to do that?

**Comment by cymcsg** [comment]
The swipe layout has been changed in the latest version.

**Comment by mori-honest** [comment]
this problem is not fixed. how can i fix it?

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue. @mori-honest
