### ISSUE TITLE
Swiping Rapidly Causes IndexOutOfBounds error Process: com.dreamteam.fitnessquest, PID: 20606     java.lang.IndexOutOfBoundsException: Invalid index 7, size is 7             at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)             at java.util.ArrayList.get(ArrayList.java:308)             at com.marshalchen.ultimaterecyclerview.swipelistview.SwipeListViewTouchListener.closeOpenedItems(SwipeListViewTouchListener.java:780)

### ISSUE THREAD

**Issue by SyedWasiHaider** [cymcsg/UltimateRecyclerView#92]
PID: 20606
    java.lang.IndexOutOfBoundsException: Invalid index 7, size is 7
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at com.marshalchen.ultimaterecyclerview.swipelistview.SwipeListViewTouchListener.closeOpenedItems(SwipeListViewTouchListener.java:780)

Can you please add the ability to override this or perhaps just check the index before using it.

**Comment by cymcsg** [comment]
Do you try  ``SwipeListViewExampleActivity``? I did not find the error.
At the same time ,I think you can control it in ``onDismiss``

**Comment by SyedWasiHaider** [comment]
Yes that is what I based my code off of. I think the problem is internal to your library since that is where the error comes from.  I forgot to mention I have the following removed because I want to be able to swipe more than one at a time.

 swipe:swipeCloseAllItemsWhenMoveList="true"
swipe:onlyOneOpenedWhenSwipe="true"

**Comment by cymcsg** [comment]
I removed these line from the demo but nothing happens.
Could you help me remove the two line from the demo and watch if the error would occur?
I should find the error before I can fix it.
